name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: cachix/install-nix-action@v27
    - uses: cachix/cachix-action@v15
      with:
        name: timemachine
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check
